set QT_HOME=C:\Qt\5.3\msvc2013_64_opengl
set QT_BIN=C:\Qt\5.3\msvc2013_64_opengl\bin
set GLM_HOME=C:\Documents\R2D2\glm
set GLFW_HOME=C:\Documents\R2D2\glfw-3.0.4
set GLFW_LIB_R=C:\Documents\R2D2\glfw-3.0.4\build\src\Release
set GLFW_LIB_D=C:\Documents\R2D2\glfw-3.0.4\build\src\Debug
set GLBINDING_HOME=C:\Documents\R2D2\glbinding
set GLBINDING_DLL_R=C:\Documents\R2D2\glbinding\build\Release
set GLBINDING_DLL_D=C:\Documents\R2D2\glbinding\build\Debug
set DOXYGEN_HOME=C:\Program Files\doxygen
set GRAPHVIZ_HOME=C:\Program Files (x86)\Graphviz2.38\bin
set CMAKE_PREFIX_PATH=C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64
set GLOBJECTS_HOME=C:\Documents\R2D2\globjects
set LIBZEUG_HOME=C:\Documents\R2D2\libzeug
set PATH=%QT_HOME%;%QT_BIN%;%GLM_HOME%;%GLBINDING_HOME%;%GLBINDING_DLL_R%;%GLBINDING_DLL_D%;%GLFW_HOME%,%GLFW_LIB_R%;%GLFW_LIB_D%;%DOXYGEN_HOME%;%GRAPHVIZ_HOME%;%GLOBJECTS_HOME%;%LIBZEUG_HOME%;%PATH%;